name: Code coverage check

on: pull_request

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    name: Checkstyle
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run check style
      uses: dbelyaev/action-checkstyle@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        checkstyle_config: ./properties/joey_checks.xml
