name: reviewdog

on: [pull_request]

jobs:
  checkstyle:
    name: checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@v1.7.1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          checkstyle_config: ./properties_file/test_checks.xml
